# Generated by Django 2.0.3 on 2018-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(max_length=12)),
                ('numToppings', models.IntegerField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
