# Generated by Django 2.0.3 on 2018-11-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181126_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('RP', 'Regular Pizza'), ('SP', 'Sicilian Pizza'), ('SU', 'Sub'), ('PA', 'Pasta'), ('SA', 'Salad'), ('DP', 'Dinner Platter')], max_length=64),
        ),
    ]
